# Generated by Django 5.2 on 2025-04-12 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAuthor', models.CharField(max_length=150)),
                ('lastNameAuthor', models.CharField(max_length=150)),
                ('nationalityAuthor', models.CharField(max_length=100)),
                ('descriptionAuthor', models.TextField()),
                ('imageAuthor', models.ImageField(blank=True, max_length=255, null=True, upload_to='book/authors/images/')),
                ('createDateAuthor', models.DateTimeField(auto_now_add=True)),
                ('updateDateAuthor', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['nameAuthor'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleBook', models.CharField(max_length=150)),
                ('publicationDateBook', models.DateField()),
                ('descriptionBook', models.TextField(blank=True, null=True)),
                ('amountBook', models.SmallIntegerField(default=1)),
                ('imageBook', models.ImageField(blank=True, max_length=255, null=True, upload_to='book/books/images/')),
                ('createDateBook', models.DateTimeField(auto_now_add=True)),
                ('updateDateBook', models.DateTimeField(auto_now=True)),
                ('authorId', models.ManyToManyField(to='book.author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['titleBook'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_days', models.SmallIntegerField(default=7)),
                ('status', models.BooleanField(default=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('expirationDate', models.DateTimeField(blank=True, null=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['book'],
            },
        ),
    ]
